# Type stub for the engine-backed SigmaContext.
#
# The runtime implementation lives only on the HiveQ platform executor
# (PySigma-backed). This .pyi is the authoring surface shipped to clients so
# strategies type-check and autocomplete; see sigma_context.py for the no-op
# client placeholder. Generated via `stubgen` from the real engine module and
# curated to drop engine-only references (SigmaStrategyBridge -> Any).
from datetime import datetime
from enum import Enum
from typing import Any

from hiveq.flow.config import AssetType as AssetType, EventLogType as EventLogType, StrategyConfig as StrategyConfig
from hiveq.flow.oms.sigma.types.order import SigmaOrder as SigmaOrder
from hiveq.flow.oms.sigma.types.portfolio import SigmaGlobalPortfolio as SigmaGlobalPortfolio, SigmaPortfolio as SigmaPortfolio
from hiveq.flow.oms.sigma.types.trade_stats import SigmaTradeStats as SigmaTradeStats
from hiveq.flow.trading_types import OrderSide as OrderSide, OrderType as OrderType

class OrderState(Enum):
    INITIALIZED: str
    SUBMITTED: str
    ACCEPTED: str
    REJECTED: str
    FILLED: str
    CANCELED: str
    DENIED: str
    EXPIRED: str
    PENDING_CANCEL: str
    PENDING_REPLACE: str

class SigmaInstrument:
    def __init__(self, symbol: str, bridge: Any) -> None: ...
    @property
    def symbol(self) -> str: ...
    @property
    def last_bar(self) -> Any: ...
    @property
    def multiplier(self) -> float: ...
    @property
    def exchange(self) -> Any: ...
    @property
    def min_tick(self) -> float: ...
    @property
    def asset_type(self) -> AssetType: ...
    @property
    def current_contract(self) -> str: ...
    @property
    def security_details(self) -> Any: ...
    @property
    def native_instrument_id(self) -> Any: ...
    @property
    def tradeStats(self) -> SigmaTradeStats: ...

class SigmaContext:
    def __init__(self, strategy_config: StrategyConfig, strategy_bridge: Any) -> None: ...
    @property
    def strategy_config(self) -> StrategyConfig: ...
    @property
    def oms_type(self) -> str: ...
    @property
    def trading_day(self) -> str | None: ...
    def subscribe_bars(self, symbols: list[str], asset_type: AssetType = ..., interval: str = '1m') -> Any: ...
    def subscribe_data(self, data_id: str, signals: list[str] = ...) -> Any: ...
    def subscribe_futures_bars(self, symbols: list[str] | None = None, root: str | None = None, contract: str | None = None, continuous: str | None = None, interval: str = '1m') -> Any: ...
    def subscribe_option_snaps(self, symbol: str, option_type: str | None = None, strike: float | None = None, expiration_type: str | datetime | None = None, underlying: str | None = None, interval: str = '1s') -> Any: ...
    def get_subscribed_option_snaps(self) -> list[dict[str, Any]]: ...
    def subscribe_trades(self, symbols: list[str], asset_type: AssetType = ...) -> Any: ...
    def subscribe_futures_trades(self, symbols: list[str] | None = None, root: str | None = None, contract: str | None = None, continuous: str | None = None) -> Any: ...
    def subscribe_index(self, symbols: list[str]) -> Any: ...
    def subscribe_index_bars(self, symbols: list[str], interval: str = '1d') -> Any: ...
    def subscribe_quotes(self, symbols: list[str] | None, asset_type: AssetType = ...) -> Any: ...
    def buy_order(self, symbol: str, quantity: float, order_type: OrderType = ..., limit_price: float = ..., stop_price: float = ..., time_in_force: str = ..., market_center: str = ...) -> SigmaOrder | None: ...
    def sell_order(self, symbol: str, quantity: float, order_type: OrderType = ..., limit_price: float = ..., stop_price: float = ..., time_in_force: str = ..., market_center: str = ...) -> SigmaOrder | None: ...
    def short_order(self, symbol: str, quantity: float, order_type: OrderType = ..., limit_price: float = ..., stop_price: float = ..., time_in_force: str = ..., market_center: str = ...) -> SigmaOrder | None: ...
    def place_order(self, symbol: str, side: OrderSide, quantity: float, order_type: OrderType, limit_price: float | None = None, stop_price: float | None = None, market_center: str = ...) -> SigmaOrder | None: ...
    def close_position(self, symbol: str, order_type: OrderType = ...) -> SigmaOrder | None: ...
    def order_to_target(self, symbol: str, target_quantity: float, order_type: OrderType = ..., limit_price: float = ...) -> SigmaOrder | None: ...
    def flatten_all(self, order_type: OrderType = ...) -> list[SigmaOrder]: ...
    def cancel_order(self, order_id: str) -> bool: ...
    def modify_order(self, order_id: str, quantity: float = ..., limit_price: float = ..., stop_price: float = ...) -> bool: ...
    def cancel_all_orders(self, symbol: str = ...) -> bool: ...
    def portfolio(self) -> SigmaPortfolio: ...
    def global_portfolio(self) -> SigmaGlobalPortfolio: ...
    def net_position(self, symbol: str) -> float: ...
    def is_flat(self, symbol: str = ...) -> bool: ...
    def is_net_long(self, symbol: str) -> bool: ...
    def is_net_short(self, symbol: str) -> bool: ...
    def quantity(self, symbol: str) -> float: ...
    def get_order_state(self, order_id: str) -> OrderState | None: ...
    def clear_pending_order(self, symbol: str) -> Any: ...
    def has_open_order(self, symbol: str = ...) -> bool: ...
    def open_order_qty(self, symbol: str) -> float: ...
    def add_event_log(self, message: str, sub_event_type: str | None = None, symbol: str | None = None, state_variable: dict[str, Any] | None = None) -> Any: ...
    def log_parameter_change(self, param_name: str, old_value: Any, new_value: Any, symbol: str | None = None) -> Any: ...
    def now(self) -> datetime | None: ...
    def now_utc(self) -> datetime | None: ...
    def set_timer(self, timer_id: str, timer_interval: Any) -> Any: ...
    def cancel_timer(self, timer_id: str) -> Any: ...
    def instrument(self, symbol: str) -> SigmaInstrument: ...
    def add_executor(self, executor_params: Any) -> Any: ...
    def stop_executor_by_id(self, executor_id: str) -> bool: ...
    def replace_executor_params_by_id(self, executor_id: str, executor_params: Any) -> bool: ...
    def get_executor_params_by_id(self, executor_id: str) -> Any: ...
    def build_executor_params(self, symbol: str, quantity: int, side: str, executor_type: str, start_time: Any | None = None, end_time: Any | None = None, min_order_size: int = 1, max_order_size: int = 100, refresh_millis: int = 100, participate_pct: float = ..., aggressive_mult: float = ..., min_notional: float = ..., max_notional: float = ..., market_center: str = ..., order_type: str = ..., time_in_force: str = ..., nbbo_size_pct: float = ..., account: str = ..., custom_fix_params: dict = ...) -> Any: ...
    def stop_executor(self, executor: Any) -> bool: ...
    def executor_state(self, executor: Any) -> str: ...
    def get_sigma_portfolio(self) -> Any: ...
    def get_sigma_order_manager(self) -> Any: ...
