"""Stub for hiveq_data.instrument_reference.symbol_parser."""
from __future__ import annotations
from typing import Any, Dict, List, Optional, Tuple


class SymbolParser:
    @staticmethod
    def parse_futures_ticker(symbol: str, start_date: Optional[str] = None, end_date: Optional[str] = None) -> Optional[Dict[str, Any]]: ...
    @staticmethod
    def parse_continuous_symbol(symbol: str) -> Dict[str, Any]: ...
    @staticmethod
    def parse_options_ticker(symbol: str) -> Optional[Dict[str, Any]]: ...
    @staticmethod
    def is_valid_futures_symbol(symbol: str, root: str) -> bool: ...
    @staticmethod
    def detect_asset_type(symbol: str) -> str: ...
    @staticmethod
    def normalize_futures_symbol(symbol: str) -> Optional[str]: ...
    @staticmethod
    def extract_root(symbol: str) -> Optional[str]: ...


def parse_futures_ticker(symbol: str, start_date: Optional[str] = None, end_date: Optional[str] = None) -> Optional[Dict[str, Any]]: ...
def parse_continuous_symbol(symbol: str) -> Dict[str, Any]: ...
def parse_options_ticker(symbol: str) -> Optional[Dict[str, Any]]: ...
def is_valid_futures_symbol(symbol: str, root: str) -> bool: ...
def detect_asset_type(symbol: str) -> str: ...
def normalize_futures_symbol(symbol: str) -> Optional[str]: ...
def extract_root(symbol: str) -> Optional[str]: ...
