from abc import ABC, abstractmethod
from dataclasses import dataclass
from datetime import datetime as datetime
from hiveq.flow.config import EventType as EventType
from hiveq.flow.data.data_types import Bar as Bar, CustomData as CustomData, ImbalanceData as ImbalanceData, IndexPrice as IndexPrice, QuoteTick as QuoteTick, SnapData as SnapData, TimerEventData as TimerEventData, TradeTick as TradeTick
from hiveq.flow.oms.sigma.types import SigmaOrder as Order, SigmaPosition as Position
from hiveq.flow.utils.timezone_utils import get_configured_timezone as get_configured_timezone, nanos_to_local_datetime as nanos_to_local_datetime
from typing import Any

class Event(ABC):
    ts_event: float
    type: EventType
    @abstractmethod
    def data(self) -> Any: ...
    @property
    def time(self) -> datetime | None: ...
    @property
    def time_utc(self) -> datetime | None: ...

class CustomDataEvent(Event):
    custom_data: CustomData
    event_id: str = ...
    type: EventType = ...
    def data(self) -> CustomData: ...

class BarEvent(Event):
    bar: Bar
    type: EventType = ...
    def data(self) -> Bar: ...

class TradeEvent(Event):
    trade: TradeTick
    type: EventType = ...
    def data(self) -> TradeTick: ...

class QuoteEvent(Event):
    quote: QuoteTick
    type: EventType = ...
    def data(self) -> QuoteTick: ...

class SnapEvent(Event):
    snap: SnapData
    type: EventType = ...
    def data(self) -> SnapData: ...

class IndexPriceEvent(Event):
    index_price: IndexPrice
    type: EventType = ...
    def data(self) -> IndexPrice: ...

class Rollover:
    continuous_symbol: str
    prev_contract: str
    current_contract: str
    ts_event: int

class RolloverEvent(Event):
    rollover: Rollover
    type: EventType = ...
    def data(self) -> Rollover: ...

class StartEvent(Event):
    type: EventType = ...
    def data(self) -> None: ...

class StopEvent(Event):
    type: EventType = ...
    def data(self) -> None: ...

class OrderEvent(Event):
    order: Order
    type: EventType = ...
    def data(self) -> Order: ...

class PositionEvent(Event):
    position: Position
    type: EventType = ...
    def data(self) -> Position: ...

class TimerEvent(Event):
    timer_event_data: TimerEventData
    type: EventType = ...
    def data(self) -> TimerEventData: ...

class ExecutorEventData:
    executor_id: str
    state: str
    symbol: str
    ts_event: int

class ExecutorEvent(Event):
    executor_data: ExecutorEventData
    type: EventType = ...
    def data(self) -> ExecutorEventData: ...

class SecurityEventData:
    event_type: str
    symbol: str
    rollover_symbol: str
    ts_event: int

class SecurityEvent(Event):
    security_data: SecurityEventData
    type: EventType = ...
    def data(self) -> SecurityEventData: ...

class ImbalanceEvent(Event):
    imbalance: ImbalanceData
    type: EventType = ...
    def data(self) -> ImbalanceData: ...
