from datetime import datetime as datetime
from hiveq.flow.utils.timezone_utils import get_configured_timezone as get_configured_timezone, nanos_to_local_datetime as nanos_to_local_datetime

class SigmaBar:
    def __init__(self, symbol: str, sigma_bar) -> None: ...
    @property
    def symbol(self) -> str: ...
    @property
    def open(self) -> float: ...
    @property
    def high(self) -> float: ...
    @property
    def low(self) -> float: ...
    @property
    def close(self) -> float: ...
    @property
    def volume(self) -> float: ...
    @property
    def ts_event(self) -> int: ...
    @property
    def ts_init(self) -> int: ...
    @property
    def time(self) -> datetime | None: ...
    @property
    def time_utc(self) -> datetime | None: ...
    @property
    def interval(self) -> str: ...
