from _typeshed import Incomplete
from datetime import datetime as datetime
from hiveq.flow.utils.timezone_utils import get_configured_timezone as get_configured_timezone, nanos_to_local_datetime as nanos_to_local_datetime

class SigmaCustomData:
    def __init__(self, symbol: str, sigma_user_data, event_id: str = '') -> None: ...
    @property
    def event_id(self) -> str: ...
    @property
    def symbol(self) -> str: ...
    @property
    def data(self) -> dict[str, str]: ...
    @property
    def header(self) -> str: ...
    @property
    def row(self) -> str: ...
    @property
    def ts_event(self) -> int: ...
    def column_data(self, column_name: str, default: Incomplete | None = None): ...
    @property
    def time(self) -> datetime | None: ...
    @property
    def time_utc(self) -> datetime | None: ...
