from _typeshed import Incomplete

logger: Incomplete

class SigmaExecutor:
    def __init__(self, sigma_executor) -> None: ...
    @property
    def executor_id(self) -> str: ...
    @property
    def state_name(self) -> str: ...
    @property
    def is_stopped(self) -> bool: ...
    @property
    def is_stopping(self) -> bool: ...
    @property
    def is_active(self) -> bool: ...
    @property
    def is_valid(self) -> bool: ...
    @property
    def leaves_qty(self) -> float: ...
    @property
    def position(self) -> float: ...
    @property
    def target_qty(self) -> float: ...
    @property
    def side(self) -> str: ...
    def stop(self) -> bool: ...
    def replace_params(self, executor_params) -> None: ...
    def executor_params(self): ...
    @property
    def raw(self): ...
