class SigmaFill:
    def __init__(self, sigma_fill) -> None: ...
    @property
    def trade_id(self) -> str: ...
    @property
    def execution_id(self) -> str: ...
    @property
    def last_qty(self) -> float: ...
    @property
    def last_px(self) -> float: ...
    @property
    def commission(self) -> float: ...
    @property
    def liquidity_side(self) -> str: ...
    @property
    def ts_event(self) -> int: ...
    @property
    def is_partial_fill(self) -> bool: ...
    @property
    def symbol(self) -> str: ...
    @property
    def side(self) -> str: ...
    @property
    def filled_qty(self) -> float: ...
    @property
    def avg_px(self) -> float: ...
