from hiveq.flow.oms.sigma.types import SigmaFill
from datetime import datetime as datetime
from hiveq.flow.trading_types import OrderSide as OrderSide, OrderStatus as OrderStatus, OrderType as OrderType
from hiveq.flow.utils.timezone_utils import get_configured_timezone as get_configured_timezone, nanos_to_local_datetime as nanos_to_local_datetime

class SigmaOrder:
    def __init__(self, sigma_order, reject_reason: str | None = None) -> None: ...
    @property
    def symbol(self) -> str: ...
    @property
    def side(self) -> OrderSide: ...
    @property
    def quantity(self) -> float: ...
    @property
    def order_type(self) -> OrderType: ...
    @property
    def time_in_force(self) -> str: ...
    @property
    def limit_price(self) -> float | None: ...
    @property
    def stop_price(self) -> float | None: ...
    @property
    def order_id(self) -> str: ...
    @property
    def client_order_id(self) -> str: ...
    @property
    def status(self) -> OrderStatus: ...
    @property
    def filled_qty(self) -> float: ...
    @property
    def leaves_qty(self) -> float: ...
    @property
    def avg_px(self) -> float | None: ...
    @property
    def last_px(self) -> float | None: ...
    @property
    def last_qty(self) -> float | None: ...
    @property
    def reject_reason(self) -> str | None: ...
    @property
    def ts_event(self) -> int: ...
    @property
    def ts_init(self) -> int: ...
    @property
    def time(self) -> datetime | None: ...
    @property
    def time_utc(self) -> datetime | None: ...
    @property
    def last_fill(self) -> SigmaFill | None: ...
    @property
    def commission(self) -> float: ...
    def commissions(self) -> list: ...
    @property
    def is_buy(self) -> bool: ...
    @property
    def is_sell(self) -> bool: ...
    @property
    def is_filled(self) -> bool: ...
    @property
    def is_open(self) -> bool: ...
    @property
    def account(self) -> str: ...
    @property
    def executor_id(self) -> str: ...
    @property
    def market_center(self) -> str: ...
    @property
    def strategy_type(self) -> str: ...
