from hiveq.flow.logger import logger as logger
from hiveq.flow.oms.sigma.strategy.base_strategy import SigmaStrategyBridge as SigmaStrategyBridge
from hiveq.flow.oms.sigma.types.position import SigmaPosition as SigmaPosition

class SigmaPortfolio:
    def __init__(self, strategy_bridge: SigmaStrategyBridge) -> None: ...
    def position(self, symbol: str) -> SigmaPosition | None: ...
    def net_position(self, symbol: str) -> float: ...
    def is_flat(self, symbol: str | None = None) -> bool: ...
    def is_net_long(self, symbol: str) -> bool: ...
    def is_net_short(self, symbol: str) -> bool: ...
    def positions(self) -> list[SigmaPosition]: ...
    def realized_pnl(self, symbol: str | None = None) -> float: ...
    def unrealized_pnl(self, symbol: str | None = None) -> float: ...
    def total_pnl(self, symbol: str | None = None) -> float: ...
    def day_pnl(self, symbol: str | None = None) -> float: ...
    @property
    def max_drawdown(self) -> float: ...
    @property
    def fees(self) -> float: ...
    @property
    def initial_capital(self) -> float: ...
    @property
    def equity(self) -> float: ...
    @property
    def cash(self) -> float: ...
    def net_exposure(self) -> float: ...
    def gross_exposure(self) -> float: ...

class SigmaGlobalPortfolio:
    def __init__(self, all_bridges: list[SigmaStrategyBridge]) -> None: ...
    def position(self, symbol: str) -> SigmaPosition | None: ...
    def net_position(self, symbol: str) -> float: ...
    def is_flat(self, symbol: str | None = None) -> bool: ...
    def is_net_long(self, symbol: str) -> bool: ...
    def is_net_short(self, symbol: str) -> bool: ...
    def positions(self) -> list[SigmaPosition]: ...
    def realized_pnl(self, symbol: str | None = None) -> float: ...
    def unrealized_pnl(self, symbol: str | None = None) -> float: ...
    def total_pnl(self, symbol: str | None = None) -> float: ...
    def day_pnl(self, symbol: str | None = None) -> float: ...
    @property
    def max_drawdown(self) -> float: ...
    @property
    def fees(self) -> float: ...
    @property
    def initial_capital(self) -> float: ...
    @property
    def equity(self) -> float: ...
    @property
    def cash(self) -> float: ...
    def net_exposure(self) -> float: ...
    def gross_exposure(self) -> float: ...
