class SigmaPosition:
    def __init__(self, sigma_position) -> None: ...
    @property
    def symbol(self) -> str: ...
    @property
    def quantity(self) -> float: ...
    @property
    def side(self) -> str: ...
    @property
    def avg_price(self) -> float: ...
    @property
    def entry_price(self) -> float: ...
    @property
    def average_price(self) -> float: ...
    @property
    def market_value(self) -> float: ...
    @property
    def realized_pnl(self) -> float: ...
    @property
    def unrealized_pnl(self) -> float: ...
    @property
    def total_pnl(self) -> float: ...
    @property
    def day_pnl(self) -> float: ...
    @property
    def notional(self) -> float: ...
    @property
    def fees(self) -> float: ...
    @property
    def is_open(self) -> bool: ...
    @property
    def is_flat(self) -> bool: ...
    @property
    def is_long(self) -> bool: ...
    @property
    def is_short(self) -> bool: ...
    @property
    def ts_event(self) -> int: ...
