from datetime import datetime as datetime
from hiveq.flow.utils.timezone_utils import get_configured_timezone as get_configured_timezone, nanos_to_local_datetime as nanos_to_local_datetime

class SigmaQuoteTick:
    def __init__(self, symbol: str, sigma_quote) -> None: ...
    @property
    def symbol(self) -> str: ...
    @property
    def bid_price(self) -> float: ...
    @property
    def bid_size(self) -> float: ...
    @property
    def ask_price(self) -> float: ...
    @property
    def ask_size(self) -> float: ...
    @property
    def ts_event(self) -> int: ...
    @property
    def exchange(self) -> str: ...
    @property
    def mid_price(self) -> float: ...
    @property
    def spread(self) -> float: ...
    @property
    def time(self) -> datetime | None: ...
    @property
    def time_utc(self) -> datetime | None: ...
