from _typeshed import Incomplete
from datetime import datetime as datetime
from hiveq.flow.utils.timezone_utils import get_configured_timezone as get_configured_timezone, nanos_to_local_datetime as nanos_to_local_datetime

class SigmaSnapData:
    def __init__(self, sigma_snap) -> None: ...
    @property
    def symbol(self) -> str: ...
    @property
    def chain(self) -> str: ...
    @property
    def underlying(self) -> str: ...
    @property
    def option_type(self) -> str: ...
    @property
    def expiration_date(self) -> str: ...
    @property
    def strike(self) -> float: ...
    @property
    def bid_px(self) -> float: ...
    @property
    def ask_px(self) -> float: ...
    @property
    def price(self) -> float: ...
    @property
    def bid_sz(self) -> int: ...
    @property
    def ask_sz(self) -> int: ...
    @property
    def size(self) -> int: ...
    @property
    def mid_price(self) -> float: ...
    @property
    def spread(self) -> float: ...
    @property
    def ts_event(self) -> int: ...
    @property
    def date(self) -> str: ...
    @property
    def time(self) -> datetime | None: ...
    @property
    def time_utc(self) -> datetime | None: ...
    def column_data(self, column_name: str, default: Incomplete | None = None): ...
