class SigmaTradeStats:
    def __init__(self, symbol: str, sigma_stats) -> None: ...
    @property
    def symbol(self) -> str: ...
    @property
    def open(self) -> float: ...
    @property
    def high(self) -> float: ...
    @property
    def low(self) -> float: ...
    @property
    def close(self) -> float: ...
    @property
    def volume(self) -> float: ...
