from datetime import datetime as datetime
from typing import Any
from hiveq.flow.utils.timezone_utils import get_configured_timezone as get_configured_timezone, nanos_to_local_datetime as nanos_to_local_datetime

class SigmaTradeTick:
    def __init__(self, symbol: str, sigma_trade) -> None: ...
    @property
    def symbol(self) -> str: ...
    @property
    def price(self) -> float: ...
    @property
    def size(self) -> float: ...
    @property
    def aggressor_side(self) -> str: ...
    @property
    def ts_event(self) -> int: ...
    @property
    def trade_id(self) -> str: ...
    @property
    def exchange(self) -> Any: ...
    @property
    def market_center(self) -> Any: ...
    @property
    def exchange_raw(self) -> str: ...
    @property
    def last_price(self) -> float: ...
    @property
    def condition(self) -> Any: ...
    @property
    def raw_trade_condition(self) -> int: ...
    @property
    def condition_raw(self) -> str: ...
    @property
    def time(self) -> datetime | None: ...
    @property
    def time_utc(self) -> datetime | None: ...
