"""Stub for hiveq.utils.datetime_utils."""
from __future__ import annotations
from typing import Optional


def current_date_string() -> str: ...
def get_prev_date(look_back_days: int, from_date=None, exchange: str = 'XNYS'): ...
def get_date_from_date_str(date_str: str): ...
def get_date_list(start_date, end_date) -> list: ...
def get_date_list_from_str(start_date: str, end_date: str) -> list: ...
