"""Stub for hiveq.driver.config_property_manager."""
from __future__ import annotations
from typing import Optional


def load_env_file(path: str, override: bool = False) -> None: ...
def load_hiveq_env() -> None: ...
def get_logger(): ...
def read_config_file(config_file_name: str, fullPath: bool = False): ...
def configure(config) -> None: ...
def use_dict(config_dict: dict) -> None: ...
def reset() -> None: ...
def snapshot(): ...
def get_properties(): ...


class DictProperties:
    def __init__(self, config): ...
    def get_property_as_string(self, property, section='default', default=None) -> Optional[str]: ...
    def get_property_as_boolean(self, property, section='default', default=None) -> Optional[bool]: ...
    def get_property_as_int(self, property, section='default', default=None) -> Optional[int]: ...
    def get_property_as_float(self, property, section='default', default=None) -> Optional[float]: ...
    def get_property_keys_as_list(self, section) -> list: ...
