"""Stub for hiveq.driver.date_time_utils."""
from __future__ import annotations


def current_date_string() -> str: ...
def get_prev_date(look_back_days: int): ...
def get_datetime_from_datetime_string(date_time_str: str): ...
def get_time_delta_seconds(date_time): ...
def now_time(): ...
def get_datetime_from_time_str(time_str: str): ...
def convert_time_zone(date_time): ...
def get_datetime_from_milliseconds(milliseconds): ...
def get_datetime_str_from_millisecods(milliseconds): ...
def get_date_from_date_str(date_str: str): ...
def get_nyse_holidays(start_year: int, end_year: int): ...
def get_pre_post_date(date, time_delta: int = 1): ...
def get_date_list(start_date, end_date) -> list: ...
def get_date_list_from_str(start_date: str, end_date: str) -> list: ...
def get_time_as_string(date_time) -> str: ...
