"""Stub for hiveq.driver.hiveq_subscriber."""
from __future__ import annotations
from typing import Optional, List


class HiveQSubscriber:
    def __init__(self, topic: str = ..., keys: Optional[List[str]] = None, **kwargs) -> None: ...
    def load(self, time_out: Optional[float] = None): ...
    def add_keys(self, keys: List[str]) -> None: ...
    def stop(self) -> None: ...
    def stopped(self) -> bool: ...
    def start(self) -> None: ...
